[package]
name = "oxidiris"
description = "A Rust TUI that leverages RSVP to stream docs to your focus point - zero eye movement required."
license = "GPL-3.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
oxidiris-core = { path = "../oxidiris-core", version = "0.2.1" }
ratatui.workspace = true
crossterm.workspace = true
clap.workspace = true
anyhow.workspace = true

[dev-dependencies]
insta.workspace = true
